name: "React-app vulnerable dependency update"

on:
  workflow_dispatch:

jobs:
  stack-migration:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Updating the vulnerable dependency to latest ones"
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          
      - name: use node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          check-latest: true
          registry-url: https://registry.npmjs.org/

      - name: update dependencies   
        run: | 
          npm install
          npm install chalk@latest
          npm install lodash@latest
        
      
